### ISSUE TITLE
Missing attributes in OBM plugin

### ISSUE THREAD

**Issue by simonelbaz** [lsc-project/lsc-obm-plugin#1]
OBM provisioning user API contain attributes that are not put by the plugin :
http://obm.org/wiki/provisioning-user-api

delegation: string, // delegation of user in OBM
delegation_target: string, // delegation target of user in OBM
nomad_allowed: boolean, // give right to user to activate nomad option
nomad_enabled: boolean, // enable / disable nomade option
nomad_local_copy: boolean, // make a copy of mail localy
nomad_mail: string // define redirection address

**Comment by rouazana** [comment]
Fixed
